language: perl
install: cpanm --notest Test::Whitespaces Time::HiRes Capture::Tiny Test::Differences
before_install: cpanm -n Devel::Cover::Report::Coveralls
script: perl Build.PL && ./Build build && cover -test -report coveralls
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
